version: "1.0"
info:
  model: int-scaffold
packages:
- name: DadaProject
  gitServerName: sumitaShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
services:
- serviceName: project.dada.integrations:test1
  packages:
  - name: DadaProject
    version: "1.0"
