version: "1.0"
info:
  model: int-scaffold
packages:
- name: DadaProject
  gitServerName: sumitaShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
